before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - amd64
    - arm64
  ldflags: -X github.com/jaxxstorm/aws-sso-creds/pkg/version.Version={{.Version}}
  binary: aws-sso-creds
  main: ./cmd/aws-sso-creds/main.go
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  prerelease: auto
brews:
  - name: aws-sso-creds
    tap:
      owner: jaxxstorm
      name: homebrew-tap
    commit_author:
      name: GitHub Actions
      email: bot@leebriggs.co.uk
    folder: Formula
    homepage: "https://leebriggs.co.uk"
    description: "Helper utility to get temporary credentials from AWS SSO."
scoop:
  url_template: "http://github.com/jaxxstorm/aws-sso-creds/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: jaxxstorm
    name: scoop-bucket
    branch: main
  commit_author:
    name: bot
    email: bot@leebriggs.co.uk
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://leebriggs.co.uk/"
  description: "Helper utility to get temporary credentials from AWS SSO."
